#spring:
#  main:
#    allow-bean-definition-overriding: true
#
#  application:
#    name: project
#
#  datasource:
##    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/quizera_db011}
##    username: ${PGUSER:postgres}
##    password: ${PGPASSWORD:postgres}
##    driver-class-name: org.postgresql.Driver
#
#  url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#  username: ${PGUSER}
#  password: ${PGPASSWORD}
#  driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: ${PORT:8084}

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: project

  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:quizera_db011}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:1929}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      connection-timeout: 20000
      initialization-fail-timeout: 60000

server:
  port: ${PORT:8084}

#spring:
#  application:
#    name: quizera
#
#  main:
#    allow-bean-definition-overriding: true
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true